pipeline {
    agent any

    environment {
        JAR_PATH = 'target/springboot-crud-0.0.1-SNAPSHOT.jar'
        DEPLOY_SERVER = '192.168.1.36'
        DEPLOY_USER = 'sai baba'
        DEPLOY_PATH = 'C:\\Users\\SAI BABA\\Downloads\\restful-using-spring-boot-master\\restful-using-spring-boot-master'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/Sairachuri/restful-using-spring-boot-master.git'
            }
        }

        stage('Build') {
            steps {
                script {
                    // Use Maven to build the project
                    bat 'mvn clean package'
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    // Path to the JAR file
                    def jarFile = "${env.WORKSPACE}\\${env.JAR_PATH}"

                    // Destination path on the Windows machine
                    def deployPath = "${env.DEPLOY_PATH}\\${env.JAR_PATH}".replace('/', '\\')

                    echo "Deploying ${jarFile} to ${deployPath}"

                    // Copy file to deployment path
                    bat "copy /Y \"${jarFile}\" \"${env.DEPLOY_PATH}\""

                    // Optional: Command to run the JAR file if needed
                    // bat "java -jar \"${deployPath}\""
                }
            }
        }
    }

    post {
        success {
            echo 'Deployment completed successfully.'
        }
        failure {
            echo 'Deployment failed.'
        }
    }
}
