pipeline {
    agent any
    environment {
        JAR_PATH = "target/springboot-crud-0.0.1-SNAPSHOT.jar"
        DEPLOY_SERVER = '192.168.1.36'
        DEPLOY_USER = 'sai baba'
        DEPLOY_PATH = 'C:/Users/SAI BABA/Downloads/restful-using-spring-boot-master/restful-using-spring-boot-master'
        JAVA_HOME = 'C:/Program Files/Java/jdk-17' // Path to JDK 17
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/Sairachuri/restful-using-spring-boot-master.git'
            }
        }

        stage('Build') {
            steps {
                bat 'mvn clean package'
            }
        }

        stage('Test') {
            steps {
                bat 'mvn test'
            }
        }

        stage('Deploy') {
            steps {
                script {
                    def copyCommand = """
                    powershell.exe -Command "Copy-Item -Path ${JAR_PATH} -Destination \\\\${DEPLOY_SERVER}\\C$\\Users\\SAI BABA\\Downloads\\restful-using-spring-boot-master\\restful-using-spring-boot-master\\"
                    """
                    def startCommand = """
                    powershell.exe -Command "Invoke-Command -ComputerName ${DEPLOY_SERVER} -Credential (New-Object PSCredential('${DEPLOY_USER}', (ConvertTo-SecureString 'your-password' -AsPlainText -Force))) -ScriptBlock { Start-Process 'java' -ArgumentList '-jar C:\\Users\\SAI BABA\\Downloads\\restful-using-spring-boot-master\\restful-using-spring-boot-master\\springboot-crud-0.0.1-SNAPSHOT.jar' -NoNewWindow -RedirectStandardOutput 'C:\\Users\\SAI BABA\\Downloads\\restful-using-spring-boot-master\\restful-using-spring-boot-master\\output.log' -RedirectStandardError 'C:\\Users\\SAI BABA\\Downloads\\restful-using-spring-boot-master\\restful-using-spring-boot-master\\error.log' -PassThru }"
                    """

                    // Execute the commands
                    bat copyCommand
                    bat startCommand
                }
            }
        }
    }

    post {
        success {
            echo 'Deployment successful!'
        }
        failure {
            echo 'Deployment failed!'
        }
    }
}
