pipeline {
    agent any

    environment {
        JAVA_HOME = 'C:\\Program Files\\Java\\jdk-17' // Ensure this path is correct
        JAR_PATH = 'target/springboot-crud-0.0.1-SNAPSHOT.jar'
        DEPLOY_SERVER = '192.168.1.36'
        DEPLOY_USER = 'sai baba'
        DEPLOY_PATH = 'C:\\Users\\SAI BABA\\Downloads\\restful-using-spring-boot-master\\restful-using-spring-boot-master'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/Sairachuri/restful-using-spring-boot-master.git'
            }
        }

        stage('Build') {
            steps {
                script {
                    bat 'mvn clean package'
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    def jarFile = "${env.WORKSPACE}\\${env.JAR_PATH}"
                    def deployPath = "${env.DEPLOY_PATH}".replace('/', '\\')

                    echo "Deploying ${jarFile} to ${deployPath}"
                    bat "copy /Y \"${jarFile}\" \"${deployPath}\""
                }
            }
        }
    }

    post {
        success {
            echo 'Deployment completed successfully.'
        }
        failure {
            echo 'Deployment failed.'
        }
    }
}
